'use client';
import { useState } from "react";
import NavBar from "../components/backend/NavBar";
import Sidebar from "../components/backend/Sidebar"; // Ensure the import path and case are correct


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({ children }) {
  const [showSidebar,setShow] = useState(true);
  return (
    <html lang="en">
      {/* <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head> */}
      <body className="min-h-screen ">
          <div className="flex gap-0.5 min-h-screen">
            {/* Sidebar */}
            <Sidebar showSidebar={showSidebar} />
            <div className="w-full">
              {/* Header */}
              <NavBar setShow={setShow} showSidebar={showSidebar} />
              <main className={showSidebar?"p-8 text-slate-50 min-h-screen mt-16 ml-60 bg-custom-gradient ":"bg-custom-gradient p-12 text-slate-50 min-h-screen min-w-screen mt-16 ml-[-2] "}>
                {children}
              </main>
            </div>
            {/* Footer */}
          </div>
        
      </body>
    </html>
  );
}
